site_name: 競プロライブラリ
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - codehilite:
      noclasses: true
      pygments_style: colorful
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - git-revision-date
  - open-in-new-tab
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
