site_name: 競プロライブラリ
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - codehilite:
      noclasses: true
      pygments_style: colorful
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - git-revision-date
  - open-in-new-tab
